name: CD | Update deployed github pages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  prepare-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13.7'

      - name: Cache logs
        id: cache-logs
        uses: actions/cache@v4.0.0
        with:
          path: |
            history/
            public/badges/
          key: saved-logs-${{ github.run_id }}

      - name: Install Python deps
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Clone MDN content repo
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: git clone https://github.com/mdn/content.git content

      - name: Clone MDN translated-content repo
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: git clone https://github.com/mdn/translated-content.git translated-content

      - name: Clone MDN translated-content-de repo
        if: steps.cache-logs.outputs.cache-hit != 'true'
        run: git clone https://github.com/mdn/translated-content-de.git translated-content-de

      - name: Download popularities current.csv
        if: steps.cache-logs.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p history
          curl -fsS https://popularities.mdn.mozilla.net/current.csv -o history/current.csv

      - name: Upload MDN content artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: mdn-content
          path: |
            content/
            translated-content/
            translated-content-de/
            history/current.csv
          if-no-files-found: error

  generate-data:
    runs-on: ubuntu-latest
    needs: prepare-repos
    strategy:
      matrix:
        locale: [ "de", "en-us", "es", "fr", "ja", "ko", "pt-br", "ru", "zh-cn", "zh-tw" ]
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package.json
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13.7'

      - name: Download MDN content artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: mdn-content
          path: .

      - name: Prepare workspace
        run: |
          mkdir -p history
          mkdir -p public/badges

      - name: Generate logs for single locale
        shell: bash
        run: |
          LOC=${{ matrix.locale }}
          if [ "$LOC" = "en-us" ]; then
            python .github/scripts/extract-mdn-logs.py content en-us history/logs-$LOC.txt
          elif [ "$LOC" = "de" ]; then
            python .github/scripts/extract-mdn-logs.py translated-content-de $LOC history/logs-$LOC.txt
          else
            python .github/scripts/extract-mdn-logs.py translated-content $LOC history/logs-$LOC.txt
          fi

      - name: Generate badge for locale
        if: ${{ matrix.locale != 'en-us' }}
        run: |
          node .github/scripts/generate-badges.cjs ${{ matrix.locale }}

      - name: Upload data artifact for locale
        uses: actions/upload-artifact@v5.0.0
        with:
          name: site-data-${{ matrix.locale }}
          path: |
            history/
            public/badges/
          if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    needs: generate-data
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install deps
        run: npm ci

      - name: Download data artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          path: .

      - name: Build
        run: npm run build

      - name: Copy history to dist
        run: cp -r history dist/history

      - name: Add 404 fallback
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.0
